# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"GAN": "01_model.ipynb",
         "ResBlock": "02_architecture_common.ipynb",
         "ResNet": "02_architecture_common.ipynb",
         "UpConv2D": "02_architecture_common.ipynb",
         "Generator": "08_architecture_DeblurGANv2.ipynb",
         "Discriminator": "08_architecture_DeblurGANv2.ipynb",
         "add_gaussian_noise": "04_dataset_common.ipynb",
         "crop": "04_dataset_common.ipynb",
         "hflip": "04_dataset_common.ipynb",
         "vflip": "04_dataset_common.ipynb",
         "rot90": "04_dataset_common.ipynb",
         "channel_shuffle": "04_dataset_common.ipynb",
         "saturation": "04_dataset_common.ipynb",
         "Dataset": "09_dataset_DeblurGANv2.ipynb",
         "Trainer": "06_trainer_MSResNet.ipynb",
         "PSNR": "07_metrics.ipynb",
         "SSIM": "07_metrics.ipynb",
         "FPNHead": "08_architecture_DeblurGANv2.ipynb",
         "FPN": "08_architecture_DeblurGANv2.ipynb",
         "instance_norm": "08_architecture_DeblurGANv2.ipynb",
         "DiffAugment": "99_diffaugment.ipynb",
         "rand_brightness": "99_diffaugment.ipynb",
         "rand_saturation": "99_diffaugment.ipynb",
         "rand_contrast": "99_diffaugment.ipynb",
         "rand_translation": "99_diffaugment.ipynb",
         "rand_cutout": "99_diffaugment.ipynb",
         "AUGMENT_FNS": "99_diffaugment.ipynb",
         "Model": "model_without_lightning.ipynb"}

modules = ["model.py",
           "architecture/common.py",
           "architecture/MSResNet.py",
           "data/common.py",
           "data/MSResNet.py",
           "trainers/MSResNet.py",
           "metrics.py",
           "architecture/DeblurGANv2.py",
           "data/DeblurGANv2.py",
           "data/diffaugment.py",
           "model_without_lightning.py"]

doc_url = "https://emirkonuk.github.io/defocus/"

git_url = "https://github.com/emirkonuk/defocus/tree/master/"

def custom_doc_links(name): return None
