# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/08_callbacks.ipynb (unless otherwise specified).

__all__ = ['DeblurGANv2Callbacks']

# Cell
import pytorch_lightning as pl

# Cell
class DeblurGANv2Callbacks(pl.Callback):
    def on_validation_model_eval(self):
        # this doesn't work as a Callback, need to call from inside the lightning module
        # I made a comment here:
        # https://github.com/PyTorchLightning/pytorch-lightning/issues/2551#issuecomment-742601083
        self.train()

    def on_epoch_start(self, trainer, pl_module):
        if trainer.current_epoch == 3:
            print("Unfreeze was called by a callback.")
            pl_module.G.unfreeze()